### PR TITLE
smartos-changelog#10 Want Triton page

### PR DESCRIPTION
**Pull request by bahamat**

### CODE REVIEW

**Comment by bahamat** [comment]
I got the changelog working.

The biggest remaining issues are:

* release-20190425-20190425T015956Z and older do not have the git hash in the directory name, so we don't have one to include with the filename. We need to fetch the directory look up the name.
* release-20150122-20150123T234428Z and older don't have a changelog at all, so we currently don't load anything. It would be nice to have download links even if we can't load the changelog.

**Comment by bahamat** [comment]
OK, I figured out that uploading an empty changelog.txt lets the page load and has download links (but they're wrong due to the missing git hash in the filename).

**Comment by bahamat** [comment]
I'd also like to be able to flag "toxic" releases. They are unfortunately inconsistently labeled.

**Comment by bahamat** [comment]
OK, I got it parsing `release.json`, and adds download links for each of usb, coal, iso, ipxe, only if available. Because it's now parsing release.json, the correct filename is always available. For coal, that includes whether or not it should be 4gb or 8gb.

I'm intentionally leaving some "cruft" that could be cleaned up in order to minimize differences with smartos.html. I'd like to do some more unification eventually.

**Review by danmcd — COMMENTED** [review]
How tested?  (And I had to look at the incremental pushes to get a sense of what you're fixing vs. just bringing over.  I may do that some more.)

**Comment by bahamat** [comment]
Testing version is here: <https://us-east.manta.joyent.com/bbennett/public/triton.html>

**Review by danmcd — APPROVED** [review]

**Review by danmcd — APPROVED** [review]

**Review by danmcd — APPROVED** [review]
Sorry I didn't catch that until after prior approval.

**Pull request merged**
